### ISSUE TITLE
No examples are provided

### ISSUE THREAD

**Issue by frahik** [tkonopka/Rcssplot#16]
It is necessary to add a couple of examples with the code to execute and the end result (the plot).
To be able to know about package and its potential in the development of software, algorithms, or results.

- [ ] Add to Readme.md some examples
- [ ] Add to wiki reproducible examples.

**Comment by tkonopka** [comment]
Thanks for your interest. There are a few examples in the package vignette folder.

library("knitr")
knit2pdf("Rcssplot.Rnw")

A pdf of the vignette is also available at the [package summary page](https://cran.r-project.org/web/packages/Rcssplot/index.html) on CRAN.

I agree some examples in html form might also be useful on the github repo. I'll try to add these in the coming days.

**Comment by tkonopka** [comment]
Updated wiki with links to gists. Closing issue.
