### ISSUE TITLE
New feature: device selectors

### ISSUE THREAD

**Issue by nfultz** [tkonopka/Rcssplot#9]
In CSS, you have `@print ...` to add rules for hardcopies.

It would be nice to have conditional rules for specific devices, eg

``` r
  @pdf abline {
    lwd: 2
  }

  @png abline {
    lwd: 5
  }
```

This would help me use the same stylesheet interactively and in knitr.

**Comment by tkonopka** [comment]
Hi nfultz,

Thanks for suggesting. This one is slightly complicated (requires changes to the lexer, parser, and wrappers for pdf() and png())

As a temporary workaround, you could use classes instead of devices, e.g. 

```
abline.pdf {
  lwd: 2;
}
abline.png {
  lwd: 5;
}
```

Then supply a class name when calling Rcssabline, e.g. 

```
Rcssabline(h=2, Rcssclass="pdf"); ## if you're using device pdf()
Rcssabline(h=2, Rcssclass="png") ## if you're using device png()
```

Cheers
